services:
  - type: web
    name: listly
    env: java
    plan: free
    autoDeploy: true
    buildCommand: "./mvnw -pl backend -DskipTests package"
    startCommand: "java -jar backend/target/Listly-backend-0.0.1-SNAPSHOT.jar"
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JAVA_TOOL_OPTIONS
        value: -Xmx300m
